version: 3

vars:
  web: django-nextjs_web_1

tasks:
  makemigrations:
    - docker exec -it {{.web}} python3 /app/manage.py makemigrations
  
  migrate:
    - docker exec -it {{.web}} python3 /app/manage.py migrate
  
  manage:
    - docker exec -it {{.web}} python3 /app/manage.py {{.CLI_ARGS}}

  generate_openapi_schema:
    - docker exec -it {{.web}} python3 /app/manage.py generateschema --title="Jobbee API" --description="OpenAPI document" --urlconf='backend.urls' > openapi-schema.yaml 
